CREATE TABLE IF NOT EXISTS livros (
  id_livro INT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(200) NOT NULL,
  isbn VARCHAR(20) NOT NULL UNIQUE,
  autor VARCHAR(150) NOT NULL,
  editora VARCHAR(100) NOT NULL,
  data_cadastro DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  data_atualizacao DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id_livro)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
